### ISSUE TITLE
New centrist category needed

### ISSUE THREAD

**Issue by jpanger24** [TheAmeliaMay/AmericanValues#1]
With the new realignment in US politics that has happened(especially since the Trump era), one can't really be culturally liberal and a Republican of any type. Maybe there needs to be some sort of centrist/New Democrat category that encompasses a lot of the people who aren't exactly Republicans anymore(if they used to be).

**Comment by TheAmeliaMay** [comment]
Thank you for your post!

There's already general "Centrist" ideology that shows up when you balance every value, but I did add two new categories: Liberal Republican and Conservative Democrat. I know these terms are sort of oxymorons, but they're the terms most people use to describe certain politicians, even of they're RINOs and DINOs.
