### ISSUE TITLE
Some questions are descriptive instead of prescriptive

### ISSUE THREAD

**Issue by Bubblebyb** [TheAmeliaMay/AmericanValues#2]
For example, the questions "Labor Unions are secretly run by communists" and "America is a Christian country." Someone taking the test may agree or disagree with these statements but have completely different opinions about the topic. One may believe that America is a Christian country while thinking that it is a negative thing or believe that labor unions are run by communists while thinking that is a positive thing.

**Comment by TheAmeliaMay** [comment]
Thank you for your post!

I've been meaning to fix those two questions for a while now, but never got around to it until I saw your post. I removed, reworded, and added a few questions on the test.
