### ISSUE TITLE
Dude, bring back the Progressive Republicans.

### ISSUE THREAD

**Issue by Nikita-bergen** [TheAmeliaMay/AmericanValues#3]
Make the liberal Republicans social and power - 40, as was the case with the progressive Republicans. Progressive Republicans still exist and are popular in New England

**Comment by TheAmeliaMay** [comment]
I have them at 65 freedom (social) and 60 authority (power). The "Progressive Republican" ideology was just a misnomer of "Liberal Republican".

**Comment by Nikita-bergen** [comment]
> У меня их 65 свобода (социальная) и 60 авторитет (власть). "Прогрессивно-Республиканская" идеология была просто неправильным названием"Либерально-Республиканской".

They should have less freedom and authority because they support small government and pro-security.

**Comment by TheAmeliaMay** [comment]
Small government translates into more freedom — as the Security value implies big government — while the power axis refers to whether power should be vested in the Constitution or government officials.

Liberal Republicans support Roe v. Wade, which used a liberal interpretation of the Constitution, which places them against Constitutionalism — which is more textualist and originalist than the Authoritarian value. I should probably rename that axis and its values, to be honest, but I'm not so sure what they should be.

**Comment by Nikita-bergen** [comment]
> Малое правительство означает большую свободу — поскольку ценность безопасности подразумевает большое правительство, — в то время как ось власти относится к тому, должна ли власть принадлежать Конституции или правительственным чиновникам.
> 
> Либеральные республиканцы поддерживают Роу против Уэйда, который использовал либеральную интерпретацию конституции, что ставит их против конституционализма — который является более текстуальным и оригиналистским, чем авторитарная ценность. Честно говоря, мне, наверное, следовало бы переименовать эту ось и ее значения, но я не совсем уверен, какими они должны быть.

I agree, we may have some fundamental and theoretical differences on these issues. Because it seems to me that Roe v. Wade follows in the bosom of constitutionalism. Security and small government do not contradict each other, since the main function of a small government is to protect citizens, etc. The problem is that in the old version I am a progressive Republican, which corresponds to my self-identification. In the new version, I am a conservative Democrat, which for me is like a dixiecrat (rubbish).

**Comment by TheAmeliaMay** [comment]
Ohhh, I see what you mean now! Send me your results and I'll look into it.

**Comment by Nikita-bergen** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/80643327/111091101-f504cb80-8542-11eb-9d3e-21c01d7c0372.png)

**Comment by TheAmeliaMay** [comment]
Thanks!
