### ISSUE TITLE
State Vs Federal Axis Too Unbalanced

### ISSUE THREAD

**Issue by MrStan53** [TheAmeliaMay/AmericanValues#5]
When I took the test, as well as sending it to multiple friends which have a variety of worldviews, almost all of them got placed into the pro centralization category. I sent a copy of it to a few of my friends who actively support our state's secession from the union, and even they were tagged in favor of centralization. I think the State versus Federal axis and the pertaining questions are far too skewed in favor of centralization and don't ask as open ended questions as some of the others. IE: the federal government should make states allow gay marriage or healthcare seems to have the same weight as you're patriotic for your region or state over your country and even you aren't opposed to secession. Perhaps rebalance it or add an extra question or two such as "local governmental laws should take precedence over federal laws" or "land management and regulation ought to be done on a state or municipal level." Also, asking about particular secessionist movements such as Jefferson also seems like a bad idea, as someone who supports Calexit or Cascadia would almost certainly put a no, as would a Pro Texan progressive not support the reformation of the CSA.

Admittedly I'm putting more effort in than I'd like into writing this but that was an observation I noticed enough for me to write about

**Comment by TheAmeliaMay** [comment]
Thanks for your post! I certainly do appreciate your effort.

I ranked pretty heavily in favor of State's Rights, but had a suspicion that I wasn't far enough in favor. This pretty much confirms that. A few of the questions should probably be removed, and I should definitely reword some of them. I'll seriously consider adding those questions you proposed; thanks for the ideas!

You're right that every question has the same weight; I couldn't figure out what the right weight actually was, so at some point I just made them all 10. I've been working on trying to balance them out, but I've have trouble figuring out what the weight should actually be. I'll take a closer look at the States axis.
