### ISSUE TITLE
I quickly went through the test again and wrote my thoughts about some of the questions (critique)

### ISSUE THREAD

**Issue by Eul0ia** [TheAmeliaMay/AmericanValues#7]
question 18 The "sex" should be changed to "biological sex" or "gender" depending on what is meant
question 42 is descriptive instead of prescriptive
11 and 12 are redundant
23 I think this is a pointless question. Everyone can agree with this
28 and 29 balanced budget very similar
30 and 31 are redundant
33 and 34 are redundant but I sort of get why they're different questions "socialized"
40 and 41 are redundant school
47 is ambiguous
50 and 52 are redundant
55, 58, and 59 are too similar
67 and 69 are redundant
89 is descriptive instead of prescriptive
96 is a weird question. I don't think it's very descriptive of any political stance
118 should just be "the electoral college is bad"
Again, these are just my thoughts.

**Comment by TheAmeliaMay** [comment]
Thanks a bunch! I really appreciate specific critiques!

I'll definitely reference this when I go through and reword the questions (which I should get around to tomorrow).
